# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      working-directory: ./geektrust
      run: chmod +x gradlew
    - name: Build with Gradle
      working-directory: ./geektrust
      run: ./gradlew build
    - name: Test with Gradle
      working-directory: ./geektrust
      run: ./gradlew test

    - name: Generate Jacoco Badge
      id: jacoco
      uses: cicirello/jacoco-badge-generator@v1.1.0
      with:
        jacoco-csv-file: ./geektrust/build/reports/jacoco/test/jacocoTestReport.csv

    - name: Log coverage percentage
      working-directory: ./geektrust
      run: |
        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
        echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

    - name: Commit the badge (if it changed)
      run: |
        if [[ `git status --porcelain` ]]; then
          git config --global user.name 'Sreeram Boyapati'
          git config --global user.email 'sreeram-boyapati@users.noreply.github.com'
          git add -A
          git commit -m "Autogenerated JaCoCo coverage badge"
          git push
        fi
      continue-on-error: true

    - name: Upload Jacoco coverage report
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-report
        path: ./geektrust/build/reports/jacoco/test/
